from __future__ import annotations

PRODUCTION_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hotpot Dashboard</title>
<style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#121a2d;--line:#26324a;--muted:#93a4bd;--text:#edf4ff;--good:#38d996;--bad:#ff6b6b;--warn:#f6c85f;--link:#9ec5ff}
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
main{max-width:1500px;margin:auto;padding:28px}.header{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-bottom:20px}.title{font-size:30px;font-weight:800}.muted{color:var(--muted)}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:12px}.card,.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.metric{font-size:28px;font-weight:800}.label{font-size:12px;text-transform:uppercase;color:var(--muted)}
.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:14px;margin-top:14px}.equal{grid-template-columns:1fr 1fr}.appgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.app{padding:12px;border:1px solid var(--line);border-radius:10px}
.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:7px}.ok{background:var(--good)}.down{background:var(--bad)}.warn{color:var(--warn)}.danger{color:var(--bad)}.good{color:var(--good)}
table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:8px;border-bottom:1px solid #202b40}code{color:#dbe8ff}a{color:var(--link);text-decoration:none}a:hover{text-decoration:underline}.row{padding:7px 0;border-bottom:1px solid #202b40}.row:last-child{border-bottom:0}.kv{display:grid;grid-template-columns:minmax(145px,.7fr) 1.3fr;gap:4px 12px;font-size:13px}.kv div:nth-child(odd){color:var(--muted)}
button{border:1px solid var(--line);background:#18223a;color:var(--text);border-radius:8px;padding:5px 9px;cursor:pointer}button:hover{border-color:#52688f}button.approve{border-color:#356b57;color:var(--good)}button.remove{border-color:#7a4747;color:#ffaaaa}button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:8px;align-items:center;margin-top:5px;flex-wrap:wrap}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:2px 7px;font-size:11px;text-transform:uppercase}.pill.high{border-color:var(--bad);color:var(--bad)}.pill.medium{border-color:var(--warn);color:var(--warn)}.pill.applied{border-color:var(--good);color:var(--good)}
@media(max-width:900px){main{padding:16px}.grid,.equal{grid-template-columns:1fr}.appgrid{grid-template-columns:1fr}.header{align-items:start;flex-direction:column}}
</style>
</head>
<body><main>
<div class="header"><div><div class="title">🔥 Hotpot</div><div class="muted">Persistent cross-app attack intelligence</div></div><div id="updated" class="muted">Loading…</div></div>
<div id="metrics" class="cards"></div>
<div class="grid"><section class="panel"><h3>Protected applications</h3><div id="apps" class="appgrid"></div></section><section class="panel"><h3>Top offenders</h3><div id="offenders"></div></section></div>
<div class="grid equal"><section class="panel"><h3>Response recommendations</h3><div id="responses"></div><h3>Active Cloudflare enforcement</h3><div id="activeEnforcement"></div></section><section class="panel"><h3>Response policy</h3><div id="responsePolicy"></div></section></div>
<div class="grid equal"><section class="panel"><h3>Top networks / ASNs</h3><div id="networks"></div></section><section class="panel"><h3>Top countries</h3><div id="countries"></div></section></div>
<div class="grid equal"><section class="panel"><h3>Operational health</h3><div id="system"></div></section><section class="panel"><h3>GeoIP / attribution</h3><div id="geoip"></div></section></div>
<div class="grid"><section class="panel"><h3>Recent activity</h3><div style="overflow:auto"><table><thead><tr><th>Time</th><th>App</th><th>Source</th><th>Category</th><th>Path</th><th>Action</th></tr></thead><tbody id="recent"></tbody></table></div></section><section class="panel"><h3>Top paths</h3><div id="paths"></div><h3>Categories</h3><div id="categories"></div><h3>Scanners</h3><div id="scanners"></div></section></div>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat().format(n||0);
const age=s=>{if(s==null)return 'n/a';s=Math.max(0,Number(s)||0);if(s<120)return Math.round(s)+'s';if(s<7200)return Math.round(s/60)+'m';if(s<172800)return (s/3600).toFixed(1)+'h';return (s/86400).toFixed(1)+'d'};
const when=v=>v?new Date(v).toLocaleString():'never';
function list(id,rows,key){document.getElementById(id).innerHTML=(rows||[]).map(x=>`<div class="row">${esc(x[key])} <span class="muted">${fmt(x.hits)}</span></div>`).join('')||'<span class="muted">No data yet</span>'}
function offenderName(o){return o.source_type==='cloudflare-worker'?'Cloudflare Worker · '+esc(o.worker_zone||'legacy/unknown zone'):esc(o.identity_key||o.ip)}
function responseAction(a){return ({watch:'Watch',recommend_challenge:'Managed challenge',recommend_block:'Block 24h',recommend_long_block:'Long block'})[a]||a}
async function actionRequest(id,verb){const r=await fetch('/api/recommendation/'+encodeURIComponent(id)+'/'+verb,{method:'POST',headers:{'X-Hotpot-Action':verb}});let body=null;try{body=await r.json()}catch(e){}if(!r.ok){const msg=body?.enforcement_error||body?.error||body?.message||await r.text().catch(()=>null)||('HTTP '+r.status);alert(verb[0].toUpperCase()+verb.slice(1)+' failed: '+msg);return false}return true}
async function dismissRec(id){if(!confirm('Dismiss this recommendation for the configured cooldown?'))return;if(await actionRequest(id,'dismiss'))await load()}
async function approveRec(id,label,target,duration){if(!confirm('Approve Cloudflare '+label+' for '+duration+' hours?\n\nTarget: '+target+'\n\nHotpot will create temporary WAF rule(s) only for the configured protected hostnames and automatically remove them at expiry.'))return;if(await actionRequest(id,'approve'))await load()}
async function removeRec(id){if(!confirm('Remove these Hotpot Cloudflare rules now?'))return;if(await actionRequest(id,'remove'))await load()}
function renderResponses(d){const rr=d.response||{},rows=rr.recommendations||[],p=rr.policy||{},cf=rr.enforcement||{};document.getElementById('responses').innerHTML=rows.slice(0,10).map(x=>{const e=x.evidence||{},actor=e.source_type==='cloudflare-worker'?'Cloudflare Worker · '+esc(e.worker_zone||'legacy/unknown zone'):esc(x.actor_key);const cls=x.confidence==='high'?'high':x.confidence==='medium'?'medium':'';const cats=(e.categories||[]).slice(0,4).join(', ');const enforceable=['recommend_challenge','recommend_block','recommend_long_block'].includes(x.action);const target=x.target_type==='cloudflare-worker-zone'?'Worker zone '+(x.target_value||''):x.target_value||'none';const approve=enforceable&&cf.configured?`<button class="approve" onclick="approveRec('${x.recommendation_id}','${esc(responseAction(x.action))}','${esc(target)}',${Number(x.duration_hours||0)})">Approve</button>`:enforceable?'<span class="muted">Cloudflare enforcement not configured</span>':'';return `<div class="row"><div><strong>${actor}</strong> · <strong class="${x.action.includes('block')?'danger':x.action==='recommend_challenge'?'warn':''}">${esc(responseAction(x.action))}</strong> <span class="pill ${cls}">${esc(x.confidence)}</span></div><div class="muted">Global L${fmt(e.global_level)} · score ${fmt(e.global_score)} · ${fmt(e.observed_hits)} hits · ${fmt(e.app_count)} apps · ${fmt(e.category_count)} categories</div>${cats?'<div class="muted">'+esc(cats)+'</div>':''}<div class="muted">Target: ${esc(target)}${x.duration_hours?' · '+fmt(x.duration_hours)+'h':''}</div><div class="actions"><a href="/api/recommendation?id=${encodeURIComponent(x.recommendation_id)}">details</a>${approve}<button onclick="dismissRec('${x.recommendation_id}')">Dismiss</button></div></div>`}).join('')||'<span class="muted">No active recommendations</span>';
 const active=rr.active_enforcements||[];document.getElementById('activeEnforcement').innerHTML=active.map(x=>{const e=x.evidence||{},target=x.target_type==='cloudflare-worker-zone'?'Worker zone '+(x.target_value||''):x.target_value||'unknown';return `<div class="row"><div><strong>${esc(x.actor_key)}</strong> <span class="pill applied">applied</span></div><div>${esc(responseAction(x.action))} · ${esc(target)}</div><div class="muted">${fmt((x.enforcement_rules||[]).length)} Cloudflare rule(s) · expires ${esc(when(x.enforcement_expires_at))}</div>${x.enforcement_error?'<div class="danger">Removal error: '+esc(x.enforcement_error)+'</div>':''}<div class="actions"><a href="/api/recommendation?id=${encodeURIComponent(x.recommendation_id)}">details</a><button class="remove" onclick="removeRec('${x.recommendation_id}')">Remove now</button></div></div>`}).join('')||'<span class="muted">No active Cloudflare enforcement</span>';
 const failures=rr.recent_failures||[];document.getElementById('responsePolicy').innerHTML=`<div class="kv"><div>Mode</div><div>${p.enabled?'Approval required':'Disabled'}</div><div>Cloudflare</div><div class="${cf.configured?'good':'warn'}">${cf.configured?'Ready':'Not configured'}</div><div>Token</div><div>${cf.token_configured?'Configured':'Missing'}</div><div>Target mappings</div><div>${fmt(cf.target_instances)} instances · ${fmt(cf.zones)} zones</div><div>Active window</div><div>${fmt(p.active_window_hours)} hours</div><div>Stale after</div><div>${fmt(p.stale_minutes)} minutes</div><div>Applied</div><div>${fmt(cf.applied)}</div><div>Overdue removal</div><div class="${cf.overdue_removal?'danger':''}">${fmt(cf.overdue_removal)}</div><div>Removal errors</div><div class="${cf.removal_errors?'danger':''}">${fmt(cf.removal_errors)}</div><div>Failed approvals</div><div class="${cf.failed?'warn':''}">${fmt(cf.failed)}</div><div>Automatic enforcement</div><div>Off — approval required</div><div>Automatic expiry/removal</div><div>On</div><div>Network/geography scoring</div><div>Off</div></div>${failures.length?'<div class="danger" style="margin-top:10px">Latest failure: '+esc(failures[0].enforcement_error||'Cloudflare apply failed')+'</div>':''}`}
async function load(){try{
 const r=await fetch('/api/overview',{cache:'no-store'});if(!r.ok)throw new Error('overview '+r.status);const d=await r.json();const s=d.summary||{};
 document.getElementById('updated').textContent='Updated '+new Date(d.generated_at).toLocaleTimeString();
 document.getElementById('metrics').innerHTML=[['Apps',s.protected_apps],['Healthy',(s.healthy_apps||0)+'/'+(s.protected_apps||0)],['Events',s.events],['Unique attackers',s.unique_ips],['Active tarpits',s.active_tarpits],['Suppressed',s.suppressed_events||0],['Global L3+',s.level3_plus||0],['High priority',s.response_high_priority||0],['Pending response',s.response_pending||0],['Applied rules',s.response_applied||0],['Lifetime attackers',s.lifetime_attackers||0],['DB MB',s.database_size_mb||0]].map(x=>`<div class="card"><div class="label">${esc(x[0])}</div><div class="metric">${esc(x[1])}</div></div>`).join('');
 document.getElementById('apps').innerHTML=(d.apps||[]).map(a=>`<div class="app"><strong><span class="dot ${a.healthy?'ok':'down'}"></span>${esc(a.name)}</strong><div class="muted">${a.healthy?'Ready':esc(a.error||a.upstream_health?.error||'Unavailable')}</div><div>${fmt(a.events)} events · ${fmt(a.unique_ips)} attackers · ${fmt(a.tarpits_active)} active tarpits</div><div class="muted">${fmt(a.proxied)} proxied · ${fmt(a.events_suppressed||0)} suppressed · ${fmt(a.telemetry_errors)} telemetry errors</div><div class="muted">${esc(a.version||'unknown')} · ${esc((a.git_sha||'unknown').slice(0,7))}${a.upstream_health?.probe_method?' · health '+esc(a.upstream_health.probe_method):''}</div></div>`).join('');
 document.getElementById('offenders').innerHTML=(d.top_offenders||[]).slice(0,10).map(o=>`<div class="row"><strong>${offenderName(o)}</strong> · <strong>Global L${fmt(o.global_level||o.level)}</strong> · score ${fmt(o.global_score||o.score)} · ${fmt(o.hits)} hits<div class="muted">${fmt(o.app_count)} apps · ${fmt(o.category_count)} categories · ${esc((o.apps||[]).join(', '))}</div>${o.network?.enriched?`<div class="muted">${o.source_type==='cloudflare-worker'?'Observed via '+esc(o.client_ip||'Cloudflare shared address')+' · ':''}${o.network.asn?'AS'+esc(o.network.asn)+' · ':''}${esc(o.network.provider||'')}${o.network.country?' · '+esc(o.network.country):''}${o.network.city?' · '+esc(o.network.city):''}</div>`:''}<div class="muted">Lifetime ${fmt(o.lifetime?.lifetime_hits||o.hits)} hits${o.lifetime?.first_seen?' · first '+esc(new Date(o.lifetime.first_seen).toLocaleDateString()):''}</div></div>`).join('')||'<span class="muted">No offenders yet</span>';
 renderResponses(d);
 document.getElementById('networks').innerHTML=(d.network_intelligence?.top_networks||[]).map(n=>{const detail=n.asn!=null?'/api/network?asn='+encodeURIComponent(n.asn):'/api/network?provider='+encodeURIComponent(n.provider||'');const apps=(n.top_apps||[]).slice(0,3).map(x=>x.instance_name).join(', ');const cats=(n.top_categories||[]).slice(0,3).map(x=>x.category).join(', ');return `<div class="row"><strong>${n.asn!=null?'AS'+esc(n.asn)+' · ':''}${esc(n.provider||'Unknown provider')}</strong> · ${fmt(n.hits)} hits · ${fmt(n.attackers)} attackers <a href="${esc(detail)}">details</a><div class="muted">${fmt(n.level3_plus)} L3+ · ${fmt(n.level4)} L4${apps?' · Targets: '+esc(apps):''}</div>${cats?'<div class="muted">Top probes: '+esc(cats)+'</div>':''}</div>`}).join('')||'<span class="muted">No attributed networks yet</span>';
 document.getElementById('countries').innerHTML=(d.network_intelligence?.top_countries||[]).map(c=>{const detail='/api/network?country='+encodeURIComponent(c.country_code||'');const apps=(c.top_apps||[]).slice(0,2).map(x=>x.instance_name).join(', ');return `<div class="row"><strong>${esc(c.country||c.country_code||'Unknown')}</strong> · ${fmt(c.hits)} hits · ${fmt(c.attackers)} attackers <a href="${esc(detail)}">details</a><div class="muted">${fmt(c.level3_plus)} L3+ · ${fmt(c.level4)} L4${apps?' · Targets: '+esc(apps):''}</div></div>`}).join('')||'<span class="muted">No attributed countries yet</span>';
 const db=d.database||{};const hk=db.last_housekeeping||{};document.getElementById('system').innerHTML=`<div class="kv"><div>Raw events</div><div>${fmt(db.raw_events)}</div><div>Retention</div><div>${fmt(db.retention_days)} days</div><div>Database</div><div>${(Number(db.size_bytes||0)/1048576).toFixed(1)} MB · WAL ${(Number(db.wal_size_bytes||0)/1048576).toFixed(1)} MB</div><div>Source resets</div><div>${fmt(db.source_resets)}</div><div>Maintenance errors</div><div class="${db.maintenance_errors?'warn':''}">${fmt(db.maintenance_errors)}</div><div>Last housekeeping</div><div>${esc(when(hk.at))}</div></div>`;
 const g=d.geoip||{},ga=g.attribution||{},gdb=g.databases||{};const asn=gdb.asn||{},city=gdb.city||{},country=gdb.country||{};const backlog=ga.backlog_is_lower_bound?fmt(ga.backlog_remaining)+'+':fmt(ga.backlog_remaining);document.getElementById('geoip').innerHTML=`<div class="kv"><div>Status</div><div>${g.enabled?'Loaded':'Disabled'}${(g.errors||[]).length?' · '+esc((g.errors||[]).join(', ')):''}</div><div>ASN DB age</div><div>${age(asn.age_seconds)}</div><div>City DB age</div><div>${age(city.age_seconds)}${!city.present&&country.present?' (country DB '+age(country.age_seconds)+')':''}</div><div>Last reload</div><div>${esc(when(g.last_reload_at))} · ${fmt(g.reload_count)} reloads</div><div>Attribution</div><div>${fmt(ga.attributed_attackers)}/${fmt(ga.lifetime_attackers)} lifetime attackers</div><div>Backlog</div><div>${backlog}</div><div>Revision</div><div><code>${esc((g.revision||'n/a').slice(0,80))}</code></div></div>`;
 document.getElementById('recent').innerHTML=(d.recent||[]).map(e=>`<tr><td>${esc(new Date(e.ts).toLocaleString())}</td><td>${esc(e.instance_name)}</td><td>${esc(e.client_ip)}</td><td>${esc(e.category)}</td><td><code>${esc(e.path)}</code></td><td>${esc(e.action)}</td></tr>`).join('');
 list('paths',d.top_paths,'path');list('categories',d.top_categories,'category');list('scanners',d.top_scanners,'scanner');
}catch(e){document.getElementById('updated').textContent='Refresh failed'}}
load();setInterval(load,15000);
</script>
</main></body></html>'''
